services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
  
  commandes:
    build: ./commandes
    ports:
      - "8000:8080"
    environment:
      - MONGO_URL=mongo
      - MONGO_DB=commandes
      - KAFKA_HOST=broker
      - KAFKA_TOPIC=commandes
    depends_on:
      - mongo

  stocks:
    build: ./stocks
    ports:
      - "8001:8080"
    environment:
      - MONGO_URL=mongo
      - MONGO_DB=commandes
      - KAFKA_HOST=broker
      - KAFKA_TOPIC=commandes
    depends_on:
      - mongo
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1